
name: Build & push docker Image to ECR

on:
  push:
    branches: [main]

permissions:
  contents: read
  id-token: write
  packages: write

jobs:
  build-push:
    runs-on: ubutu-latest
    steps: 

      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}
        
      - uses: aws-action/aws-ecr-login@v2

      - uses: aws-actions/build-push-action@v6
        with:
          content : .
          push: true
          tags: ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/${{ ECR_REPOSITORY}}:v${{ github.run_number }}
